version: '3.8'
services: 
  dev-db:
    image: postgres:15
    ports: 
      - 5434:5432
    environment:
      POSTGRESS_USER: postgres
      POSTGRES_PASSWORD  : 123
      POSTGRESS_DB: nest
    networks:
      - saas_ecommerce

  test-db:
    image: postgres:15
    ports: 
      - 5435:5432
    environment:
      POSTGRESS_USER: postgres
      POSTGRES_PASSWORD  : 123
      POSTGRESS_DB: nest
    networks:
      - saas_ecommerce
      
networks:
  saas_ecommerce:
